'use strict';

/** @type {import('sequelize-cli').Migration} */
module.exports = {
  async up(queryInterface, Sequelize) {
    await queryInterface.bulkInsert('Answers', [
      {
        answer: '4',
        questionId: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        answer: 'четыре',
        questionId: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        answer: '12',
        questionId: 2,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        answer: 'двенадцать',
        questionId: 2,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        answer: 'бесконечно много',
        questionId: 2,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        answer: 'Испания',
        questionId: 3,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        answer: 'в испании',
        questionId: 3,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        answer: 'об этом знает только Серёга',
        questionId: 3,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        answer: 'об этом знает только Серега',
        questionId: 3,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        answer: 'Ярик Первушин',
        questionId: 4,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        answer: 'Ярослав',
        questionId: 4,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        answer: 'Первушин',
        questionId: 4,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        answer: 'Ярик',
        questionId: 4,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        answer: 'Антон',
        questionId: 5,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        answer: 'Антон Атнагулов',
        questionId: 5,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        answer: '8',
        questionId: 6,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        answer: 'восемь',
        questionId: 6,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        answer: 'минус один',
        questionId: 7,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        answer: '-1',
        questionId: 7,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        answer: '- один',
        questionId: 7,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        answer: 'минус 1',
        questionId: 7,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        answer: '5',
        questionId: 8,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        answer: 'пять',
        questionId: 8,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        answer: '3',
        questionId: 8,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        answer: 'три',
        questionId: 8,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        answer: '4',
        questionId: 9,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        answer: 'четыре',
        questionId: 9,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        answer: 'O(n log n)',
        questionId: 10,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        answer: 'о от н логарифм н',
        questionId: 10,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        answer: '6',
        questionId: 11,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        answer: 'шесть',
        questionId: 11,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        answer: 'Волчанка',
        questionId: 12,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        answer: 'Офис',
        questionId: 13,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        answer: 'о флагах',
        questionId: 14,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        answer: 'Флаги',
        questionId: 14,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        answer: 'флаг',
        questionId: 14,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        answer: 'Про флаги',
        questionId: 14,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        answer: 'джеймс макгилл',
        questionId: 15,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        answer: 'джеймс морган макгилл',
        questionId: 15,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        answer: 'джимми макгилл',
        questionId: 15,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        answer: '8',
        questionId: 16,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        answer: 'восемь',
        questionId: 16,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        answer: '9',
        questionId: 16,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        answer: 'девять',
        questionId: 16,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        answer: 'китайский',
        questionId: 17,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        answer: 'китайский язык',
        questionId: 17,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        answer: '24',
        questionId: 18,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        answer: 'двадцать четыре',
        questionId: 18,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        answer: 'рош ха-шана',
        questionId: 19,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        answer: 'рош ха шана',
        questionId: 19,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        answer: 'рошхашана',
        questionId: 19,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        answer: 'эскимо пай',
        questionId: 20,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        answer: 'эскимопай',
        questionId: 20,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    ]);
  },

  async down(queryInterface) {
    await queryInterface.bulkDelete('Answers', null);
  },
};
